### ISSUE TITLE
Cloudflare worker to host JSON

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/supported-networks#15]
Perhaps GitHub release is sufficient, investigate if Cloudflare worker is required

**Comment by YaroShkvorets** [comment]
Implemented in github actions by deploying to github pages: 
 https://graphregistry.pages.dev/TheGraphNetworksRegistry_v0_1_0.json

Deployment is done by the entire directory. You can't seem to upload a single file, which is not ideal if we want to keep all historical JSONs in one place.
