### ISSUE TITLE
Token Logo Design for missing Web3Icons

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/supported-networks#16]
## Missing icons

- [x] Unichain
- [x] ~~XLayer~~ https://tokenicons.io/?type=network&variant=mono&icon=x-layer
- [x] Moonbase Alpha
- [x] ~~Arweave~~ https://tokenicons.io/?type=token&variant=mono&icon=arweave

## Steps to add Logo

- identity which network does not contain a logo in https://tokenicons.io/
- design 32x32 SVG logos for those missing chains
- Submit PR to get merged in https://github.com/0xa3k5/web3icons

## Questions
- For WAX, need clarification on distinguishing between WAX token and WAX chain.

**Comment by m1kecrook** [comment]
Will have the remaining 2 done today for the missing logos

**Comment by YaroShkvorets** [comment]
Also we are missing Arweave. Can we add it too? Should be easy to make.

**Comment by DenisCarriere** [comment]
@YaroShkvorets Arweave is included, it's just the name is `AR`

<img width="280" alt="image" src="https://github.com/user-attachments/assets/3b3492a7-898e-4d01-abfd-4700a75fc0d1">

https://tokenicons.io/?type=token&variant=mono&icon=arweave

**Comment by YaroShkvorets** [comment]
Looks like it's also included as a token, but not as a network. If we could add it as network with "arweave" name that'd be great.

**Comment by YaroShkvorets** [comment]
AR is native token of Arweave network

**Comment by DenisCarriere** [comment]
As for tokens as networks, there's a few others like that, WAX being one of them, I'm sure there's a few more

Would need to re-run that script, can add that logic in: https://github.com/pinax-network/supported-networks/blob/main/scripts/download/web3icons-missing.ts

**Comment by DenisCarriere** [comment]
Tokens which should also support Networks:
- Harmony
- WAX
- EOS (has EOS EVM instead)

**Comment by martybe** [comment]
Here are the icons for Unichain and Moonbase Alpha:
![Unichain Icon - Vibrant_TokenLogo_Mono](https://github.com/user-attachments/assets/94af4d25-c0d8-449a-939e-7323c43c075c)
![Unichain Icon - Vibrant_TokenLogo_Branded](https://github.com/user-attachments/assets/ce79f97e-750c-4506-b371-f3e6cce7cf97)
![chain-light Moonbase Icon_TokenLogo_Mono](https://github.com/user-attachments/assets/c5ab706c-ed01-4c84-8a51-37adf5c85e32)
![chain-light Moonbase Icon_TokenLogo_Branded](https://github.com/user-attachments/assets/ce550f63-f0ac-40ce-88a2-caac1ed17bfc)

**Comment by YaroShkvorets** [comment]
New chains added. Nice.

> networks: unichain, optopia, orderly, arweave, moonbeam, fluence, harmony

https://github.com/0xa3k5/web3icons/pull/38
