### ISSUE TITLE
Define `studio` services

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/supported-networks#18]
How do we want to identity Studio support for a particular chain

## Questions
- [ ] Are there multiple "studio" integration by various service providers?
- [ ] Can different service provider offer studio services to different chains?
- [ ] How to display Studio support when multiple service providers offer Studio support?
- [ ] How does a service provider define their studio support per chain?
- [ ] What is the URL schema for studio support?

**Comment by YaroShkvorets** [comment]
duplicate
