### ISSUE TITLE
Generate `networks.json` JSON file

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/supported-networks#3]
- [ ] Generate JSON file from all files pulled from `_data/` directory
- [ ] Define Typespec Definition for final JSON file
- [ ] Output JSON file as:
  1. `networks.json`
  2. `chains.json`
- [ ] GitHub ignore generated JSON file (to prevent bloating GitHub repo with large file updates)

**Comment by YaroShkvorets** [comment]
Implemented in #21 - see `bun generate`
