### ISSUE TITLE
Remove `issuanceRewards`?

### ISSUE THREAD

**Issue by YaroShkvorets** [pinax-network/supported-networks#31]
During the discussion with E&N the issue with `issuanceRewards` was raised and potential conflicts if it goes out of date.

> Iain McCown
> I want to bring that topic up again, we didn't quite have time to close it out in the meeting. I think including issuanceRewards in the schema could lead to problems down the road, as it will inevitably diverge from what is onchain. Unless we can come up with a reliable way to ensure that doesn't happen
> 
> Downstream applications using the [EBO subgraph](https://thegraph.com/explorer/subgraphs/4KFYqUWRTZQ9gn7GPHC6YQ2q15chJfVrX43ezYcwkgxB?view=Query&chain=arbitrum-one) to determine what chains have issuance enabled would be my suggestion

Pro: 
- No need to query EBO subgraph for non-critical application like docs, website, etc
- We can validate the field on PR and on cron against the EBO subgraph and create an issue if it goes out of sync  
- That's not something that happens often

Con:
- Can be out of sync for a period between the DAO approval and registry update
- Can't be used as a source of truth, so can lead to confusion

**Comment by YaroShkvorets** [comment]
Query to get a list of active networks:
```
{
  networks(where: { removedAt: null }) {
    id
    blockNumbers(first: 1, orderBy: blockNumber, orderDirection: desc) {
      blockNumber
    }
    alias
  }
}
```

**Comment by matthewdarwin** [comment]
Can write a github action to poll the network subgraph to get the info and then push it into the supported networks?

**Comment by YaroShkvorets** [comment]
I'm inclined to keep that field. 
Some consumers, like docs, might not want to deal with managing api keys to query the subgraph.
If your application is sensitive you should query the subgraph instead of that field

- Added validation step that fetches a list of networks from EBO subgraph and validates registry against it.
- TODO: add crontab action that would do validation once a day and create an issue if validation fails
