### ISSUE TITLE
Validate that id and aliases are unique

### ISSUE THREAD

**Issue by leoyvens** [pinax-network/supported-networks#47]
An id or alias should never appear twice in the networks list, allowing an id or alias to serve as an unique identifier of the network. This is probably already the case, but a validation check run on CI should be added to enforce this property.

**Comment by YaroShkvorets** [comment]
Already implemented in CI

**Comment by YaroShkvorets** [comment]
Leo
  [Yesterday at 3:03 PM](https://pinaxworkspace.slack.com/archives/C02RRP8H8LU/p1731009781372899?thread_ts=1730907730.710249&cid=C02RRP8H8LU)
as a detail, are you validating uniqueness across ids and aliases?

**Comment by YaroShkvorets** [comment]
Implemented
