### ISSUE TITLE
Test if Graph ID's are matching

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/supported-networks#7]
Check to see if Graph ID is match in the following:
- [ ] `chains` (`id` must match `filename`)
- [ ] `icons` (`filename` must match `id`)
- [ ] `blocks` (`filename` must match `id`)
- [ ] `providers` (services.id must match `id`)
  - [ ] rpc
  - [ ] firehose
  - [ ] substreams

**Comment by YaroShkvorets** [comment]
Providers registry is out of scope as discussed
