### ISSUE TITLE
Check if `block.url` is a valid Buf Build URL

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/supported-networks#8]
## Test on every PR
- [ ] Check if `block.url` is a valid Buf Build URL (Ex: `buf.build/streamingfast/firehose-cosmos`)
  - [ ] `startsWith` buf.build

## Tests on release
- [ ] fetch URL contents
  - [ ] match if `type` exists in content

**Comment by YaroShkvorets** [comment]
Implemented in https://github.com/pinax-network/supported-networks/pull/21
