### ISSUE TITLE
Extend Typespec definitions

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/supported-networks#9]
In the `./typespec` directory, extend the definitions based on community feedback
- [ ] Gather feedback for Typespec definitions

### `blocks.tsp`
- [ ] any other Buf requirements?
### `chains.tsp` (mainly used as reference to other registries ex: `chainId/block/networkId` )
- [ ] any other ID's required for chain matching?
  - [ ] CoinGecko? https://www.coingecko.com/en/chains
  - [ ] CMC? 
### `icons.tsp`
- [ ] How to implement Dark/Light mode?
- [ ] Do we provide single or multiple icons? (Array vs. Object)
- [ ] Which image file formats do we allow? (ex: png/jpg only?)
- [ ] Do we allow vector images? (svg)
### `providers.tsp`
- [ ] which other services are required?
- [ ] Any other additional metadata of provider required?

**Comment by YaroShkvorets** [comment]
replaced with json-schema in #21
